# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customfiler', '0001_initial'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='files',
            field=models.ManyToManyField(related_name='in_clipboards', through='filer.ClipboardItem', to='customfiler.File', verbose_name='files'),
        ),
        migrations.AddField(
            model_name='clipboarditem',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customfiler.File', verbose_name='file'),
            preserve_default=False,
        ),
    ]
